### users auth routes-############################################################################
### Create Admin ##################################################################################
POST  http://localhost:3000/api/users/create_admin
Content-Type: application/json

{
    "username": "admin",
    "password": "adminP@ssword"
}
### Login as admin
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminP@ssword"
}
### Login as simpleUser
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "simpleUser@gmail.com",
    "password": "simpleUserP@ssword"
}
### Create account
POST  http://localhost:3000/auth/create_account
Content-Type: application/json

{
    "username": "simpleUser@gmail.com",
    "password": "simpleUserP@ssword"
}
### Users ############################################################################

###[Read] get users
GET http://localhost:3000/api/users
###[Read] get user
GET http://localhost:3000/api/users/63eddf5343b0770ef7911102
###[Create] Create new user with all permissions and details
POST  http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "simpleUser@gmail.com",
    "firstName": "Simple",
    "lastName": "User",
    "sessionTimeout": "10",
    "permissions":[
        "View Subscriptions",
        "View Movies"
    ]
}
###[Update] update user details
PATCH  http://localhost:3000/api/users/63ede2d43250ca324c9f512c
Content-Type: application/json

{
    "username": "simpleUserUpdated@gmail.com",
    "firstName": "Simple",
    "lastName": "User 2",
    "sessionTimeout": "20",
    "permissions":[
        "View Subscriptions",
        "View Movies",
        "Create  Movie"
    ]
}
###[Delete] byID
DELETE http://localhost:3000/api/users/63ede2d43250ca324c9f512c

###subscripptionsWS -############################################################################
### Members [Create]
POST  http://localhost:3000/api/subscriptions_ws/members
Content-Type: application/json

{
    "name": "Elon Mask",
    "email": "Elon@gmail.com",
    "city": "Californaia"
}
###[Read]
GET http://localhost:3000/api/subscriptions_ws/members
###[Read] byID
GET http://localhost:3000/api/subscriptions_ws/members/63edce782cec98a892bb7e9a
###[Update]
PATCH  http://localhost:3000/api/subscriptions_ws/members/63edce782cec98a892bb7e9a
Content-Type: application/json

{
    "name": "Eylon Mask",
    "email": "Eylon@gmail.com",
    "city": "Californaia"
}
###[Delete]
DELETE  http://localhost:3000/api/subscriptions_ws/members/63edce782cec98a892bb7e9a
###

### Movies -#########################################################################################################
###[Create]
POST  http://localhost:3000/api/subscriptions_ws/movies
Content-Type: application/json

{
    "name" : "Titanic",
    "genres" : ["Drama", "Action", "Thriller"],
    "image" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXabh6Wr_g9AUj0soigYnWiNUAlbWRrcGnladrWxwxuA&s",
    "premiered" : "1997"
}
###[Read]
GET http://localhost:3000/api/subscriptions_ws/movies
###[Read] byID
GET http://localhost:3000/api/subscriptions_ws/movies/63edd9eac4cf0918eb73366d
###[Update]
PATCH  http://localhost:3000/api/subscriptions_ws/movies/63edd9eac4cf0918eb73366d
Content-Type: application/json

{
    "premiered" : "2001"
}
###[Delete]
DELETE  http://localhost:3000/api/subscriptions_ws/movies/63edd9d4c4cf0918eb733669
###

### Subscriptions #################################################################################################

###CRUD Subscriptions -
###[Create]
POST  http://localhost:3000/api/subscriptions_ws/subscriptions
Content-Type: application/json

{
    "memberId" : "63dbb352cebbacf220af72dc",
    "movieIdAndDateObj" : {
                "movieId" :"63ecdf17383b7045cf1bfe3f",
                "date" : "2023-05-02"
    }
}
###[Read]
GET http://localhost:3000/api/subscriptions_ws/subscriptions
###[Read] byID
GET http://localhost:3000/api/subscriptions_ws/subscriptions/63dbee35d006ebabcca76f30

###[Delete]
DELETE  http://localhost:3000/api/subscriptions_ws/subscriptions/63dbee35d006ebabcca76f30
###